### ISSUE TITLE
Question: how does getDevice work?

### ISSUE THREAD

**Issue by jeffkowalski** [RByers/pooltemp#1]
First, thanks for providing a great example for connecting right to the AquaLink system.  I'd been working on a similar project for the past several months, and was delighted when I found your code just a few days ago.
Second, sorry to ask a question in your issues log, but it seemed the best place.

I'm using Ruby for my client, rather than node.js, but fortunately your code is very legible and easily transcoded.  The login step gives me the expected result, with a json package containing a dozen fields, among them the expected id, and authorization_token, and session_id.  So far so good.

But then I cannot get the getDevice call to work.  I'm using the same kept-alive session from the prior POST for the getDevice GET

I compose a URI that looks appropriate (values slightly obfuscated here for privacy):
```https://support.iaqualink.com/devices.json?api_key=EOOEMOW4YR6QNB07&authentication_token=RGbrtgadxHsSA9P2b1sh&user_id=12345```
and use what seem like reasonable headers:
```{"accept-encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "accept"=>["*/*"], "user-agent"=>["Ruby"]}```
But I get a disappointing response:
```
#<Net::HTTPUnauthorized:0x0055660b701720>
date = Tue, 22 May 2018 00:32:48 GMT
content-type = application/json; charset=utf-8
transfer-encoding = chunked
connection = keep-alive
status = 401 Unauthorized
cache-control = max-age=5, private
access-control-allow-origin = *
access-control-max-age = 1800
x-xss-protection = 1; mode=block
x-request-id = 0e502bbd-53bb-4e84-990e-b30b0096e20b
access-control-allow-headers = origin, content-type, X-Requested-With
access-control-allow-methods = GET, POST, PUT, OPTIONS, DELETE, PATCH
x-runtime = 0.035728
x-frame-options = SAMEORIGIN
x-content-type-options = nosniff
x-powered-by = Phusion Passenger 5.2.1
server = nginx/1.12.2 + Phusion Passenger 5.2.1
{"status":"401","error":{"error_code":"error_auth_required","message":"Authorization Required","details":"Please provide proper authentication details."}}
```

Have you ever encountered something similar?  Would you share your headers or other communication details in that getDevice fetch that might point me in the right direction?

Thanks,
Jeff

**Comment by jeffkowalski** [comment]
Resolved.  Sorry for what was likely a false alarm.  Ultimately, I believe I was using an improperly formed URI.  The following ruby statements work properly:
```
api_key = 'EOOEMOW4YR6QNB07'
CREDENTIALS_PATH = "credentials.yml"
credentials = YAML.load_file CREDENTIALS_PATH

res = RestClient.post 'https://support.iaqualink.com/users/sign_in.json',
		      {api_key: api_key,
		       email: credentials[:username],
		       password: credentials[:password]}
session = JSON::parse res

res = RestClient.get "https://support.iaqualink.com/devices.json",
		     {params: {api_key: api_key,
			       authentication_token: session['authentication_token'],
			       user_id: session['id']}}
devices = JSON::parse res

res = RestClient.get 'https://iaqualink-api.realtime.io/v1/mobile/session.json',
		 {params: {actionID: 'command',
			   command: 'get_home',
			   serial: devices[0]['serial_number'],
			   sessionID: session['session_id']}}
puts res
```

**Comment by blysik** [comment]
@jeffkowalski Jeff, I'm a ruby guy too.  Do you have a ruby iaqualink project posted somewhere?  I'd love to see it, and possibly contribute.  Thanks!

**Comment by bootsie123** [comment]
Do any of you know the different endpoints for support.iaqualink.com and for iaqualink-api.realtime.io?

**Comment by jeffkowalski** [comment]
@blysik, I put my code here:
https://github.com/jeffkowalski/jandy

**Comment by BruceTrevarthen** [comment]
Is it possible to query the device itself, rather than the cloud service?  when I hit the IP/URL for the device device on my network it responds with "the URI does not exist"
